version: 1.2.0.{build}
image: Visual Studio 2022
environment:
  CoverallsRepoToken:
    secure: ejW6wWM/UFiJrab/vcmLNmkgUU+nb3R4uPC3yLgEoQ5+74P+WZ2o+K0Vf+LShFSQ
install:
- ps: >-
    Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile './dotnet-install.ps1'

    ./dotnet-install.ps1 -JSonFile global.json -InstallDir 'C:\Program Files\dotnet'
build_script:
- ps: >-
    dotnet tool restore

    dotnet cake --Target="Coverage-Report"
