version: 1.0.0.{build}
image: Visual Studio 2017
environment:
  CoverallsRepoToken:
    secure: ejW6wWM/UFiJrab/vcmLNmkgUU+nb3R4uPC3yLgEoQ5+74P+WZ2o+K0Vf+LShFSQ
build_script:
- ps: ./build.ps1 -Target Coverage-Report