version: 1.1.0.{build}
image: Visual Studio 2019
environment:
  Configuration: Release
  CoverallsRepoToken:
    secure: ejW6wWM/UFiJrab/vcmLNmkgUU+nb3R4uPC3yLgEoQ5+74P+WZ2o+K0Vf+LShFSQ
install:
- ps: >-
    Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile './dotnet-install.ps1'

    ./dotnet-install.ps1 -JSonFile global.json -InstallDir 'C:\Program Files\dotnet'
build_script:
- ps: ./build.ps1 --Target="Coverage-Report" --Configuration="$env:Configuration"